---
    environment: production
    chdir: /var/www/music.lab37.com
    address: 127.0.0.1
    user: root
    group: root
    port: 4567
    pid: /var/www/music.lab37.com/tmp/thin.pid
    rackup: /var/www/music.lab37.com/config_production.ru
    log: /var/www/music.lab37.com/log/thin.log
    max_conns: 1024
    timeout: 30
    max_persistent_conns: 512
    daemonize: true